create table if not exists public.dylan_heartbeat_runs (
  id bigint generated by default as identity primary key,
  run_slot timestamptz not null unique,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running', 'skipped', 'no_action', 'pushed', 'push_failed', 'error')),
  reason text,
  last_kelivo_end_at timestamptz,
  push_title text,
  push_body text,
  diary_content text,
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0
);

create index if not exists dylan_heartbeat_runs_started_at_idx
  on public.dylan_heartbeat_runs (started_at desc);

create index if not exists dylan_heartbeat_runs_status_started_at_idx
  on public.dylan_heartbeat_runs (status, started_at desc);

alter table public.dylan_heartbeat_runs enable row level security;

create table if not exists public.dylan_heartbeat_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default true,
  attention_window_start_minute integer not null default 1140
    check (attention_window_start_minute between 0 and 1439),
  attention_window_end_minute integer not null default 90
    check (attention_window_end_minute between 0 and 1439),
  attention_wake_after_minutes integer not null default 60
    check (attention_wake_after_minutes > 0),
  off_hours_wake_after_minutes integer not null default 180
    check (off_hours_wake_after_minutes > 0),
  attention_check_interval_minutes integer not null default 30
    check (attention_check_interval_minutes > 0),
  off_hours_check_interval_minutes integer not null default 180
    check (off_hours_check_interval_minutes > 0),
  min_push_gap_minutes integer not null default 0 check (min_push_gap_minutes >= 0),
  chat_app_name text not null default 'Kelivo',
  max_tokens integer not null default 256 check (max_tokens between 32 and 2048),
  wake_if_no_activity boolean not null default false,
  weather_enabled boolean not null default false,
  weather_location_name text not null default 'Hangzhou',
  weather_lat double precision,
  weather_lon double precision,
  updated_at timestamptz not null default now()
);

insert into public.dylan_heartbeat_settings (id)
values (true)
on conflict (id) do nothing;

alter table public.dylan_heartbeat_settings enable row level security;

comment on table public.dylan_heartbeat_runs is
  'Execution log and duplicate protection for the Dylan Heartbeat Edge Function.';

comment on table public.dylan_heartbeat_settings is
  'Editable non-secret settings for the Dylan Heartbeat Edge Function. This table contains one row.';
